### ISSUE TITLE
Border is glitchy when shaders are enabled

### ISSUE THREAD

**Issue by john32b** [john32b/futureknightdx#2]
![Screenshot_4](https://user-images.githubusercontent.com/6090296/187707732-6b49350e-b342-4064-9482-4a6ebe6baeaf.png)

On the Main Menu, if shaders are enabled, the border gets affected also, and it shouldn't.

I am adding the border object as an openFL Sprite, sibling to FlxGame. Only FlxGame has filters enabled. 

Only HashLink has this problem, HTML5, C++ work fine with this border approach.

Is there any way to fix or HACK a way around this, *(without disabling the border entirely in HL builds)*

I'd like to have an HL version, as it is much more convenient and faster to compile than C++
The code for adding the border is in `Reg.hx`

```haxe
public static function setBorder(state:Bool)
{
  if (border == null) {
	  border = new Bitmap(FlxAssets.getBitmapData(Reg.IM.STATIC.overlay_scr), cast 2, true);
  }
  if (state){
	  FlxG.stage.addChild(border);
  }else{
	  FlxG.stage.removeChild(border);
  }
}
```

**Comment by thecocce** [comment]
Hi, I tried HL version and seems to work fine.

![fn](https://github.com/john32b/futureknightdx/assets/3259703/c63e863b-4371-4135-bbbf-83b2694751a8)
![fn](https://github.com/john32b/futureknightdx/assets/3259703/d8972316-91ae-4bed-b223-9e2c6c1bb98e)
![fn](https://github.com/john32b/futureknightdx/assets/3259703/c8c3a886-0291-4015-86fd-dde492076b3b)

**Comment by john32b** [comment]
yep, the new versions fixed this, it's all the other things that they broke :face_with_spiral_eyes: :sweat_smile:
